[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hqqsvd"
version = "0.1.0"
description = "hqq quantization with svd"
dependencies = [
    "torch",
]